package com.binance.api.client.domain.account.request;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Optional;

/**
 * Request object for canceling an order.
 */
public class CancelOrderRequest extends OrderRequest {

  @JsonCreator
  public CancelOrderRequest(@JsonProperty("symbol") String symbol,
                            @JsonProperty("recvWindow") Optional<Long> recvWindow,
                            @JsonProperty("timestamp") Optional<Long> timestamp,
                            @JsonProperty("orderId") Optional<Long> orderId,
                            @JsonProperty("origClientOrderId") Optional<String> origClientOrderId,
                            @JsonProperty("newClientOrderId") Optional<String> newClientOrderId) {
    super(symbol, recvWindow, timestamp);
    this.orderId = orderId;
    this.origClientOrderId = origClientOrderId;
    this.newClientOrderId = newClientOrderId;
  }

  public CancelOrderRequest(String symbol, Long orderId) {
    super(symbol);
    this.orderId = Optional.of(orderId);
    origClientOrderId = Optional.empty();
    newClientOrderId = Optional.empty();
  }

  public final Optional<Long> orderId;

  public final Optional<String> origClientOrderId;

  /**
   * Used to uniquely identify this cancel. Automatically generated by default.
   */
  public final Optional<String> newClientOrderId;

}
